#pragma once

#include "Plugin_PresetList.h"

// ═══════════════════════════════════════════════════════════════════════════════
// PRESET INITIALIZATION
// ═══════════════════════════════════════════════════════════════════════════════
//
// DO NOT EDIT THIS FILE TO ADD PRESETS!
// Edit Plugin_PresetList.h instead - presets are defined there.
//
// This file provides InitPresets() which iterates kPresetDefs[] and registers
// each preset with the plugin. It handles both default presets and custom
// presets with specific parameter values.
//
// ═══════════════════════════════════════════════════════════════════════════════

// NOTE: This file must be included AFTER Plugin.h in Plugin.cpp
// It uses iplug::Plugin class from those headers.

// ═══════════════════════════════════════════════════════════════════════════════
// NO VALIDATION NEEDED!
// Presets now use kParamXxx values directly from Plugin_Params.h.
// No P:: namespace, no manual index sync - just the actual enum values.
// ═══════════════════════════════════════════════════════════════════════════════

inline void InitPresets(iplug::Plugin* pPlugin)
{
  for (int i = 0; i < kPresetCount; i++)
  {
    const PresetDef& preset = kPresetDefs[i];

    if (preset.isDefault)
    {
      // Default preset - uses all default parameter values
      pPlugin->MakeDefaultPreset(preset.name);
    }
    else
    {
      // Custom preset - count params and apply them
      // First, count parameters (until END sentinel)
      int paramCount = 0;
      while (paramCount < kMaxPresetParams && preset.params[paramCount].idx != END)
      {
        paramCount++;
      }

      // Create preset with default values first
      pPlugin->MakeDefaultPreset(preset.name);

      // Then override specific parameters
      // Note: We can't use MakePresetFromNamedParams easily with a runtime array,
      // so we set params individually after creating a default preset
      for (int p = 0; p < paramCount; p++)
      {
        pPlugin->GetParam(preset.params[p].idx)->Set(preset.params[p].val);
      }

      // Store the preset (MakeDefaultPreset already did this, but the values
      // were defaults - we need to re-store with our custom values)
      // Use ModifyCurrentPreset to update the stored preset data
      pPlugin->ModifyCurrentPreset(preset.name);
    }
  }

  // Reset to first preset after initialization
  pPlugin->RestorePreset(0);
}
