#pragma once

#include "Plugin_PresetList.h"

// ═══════════════════════════════════════════════════════════════════════════════
// PRESET INITIALIZATION
// ═══════════════════════════════════════════════════════════════════════════════
//
// DO NOT EDIT THIS FILE TO ADD PRESETS!
// Edit Plugin_PresetList.h instead - presets are defined there.
//
// This file provides InitPresets() which iterates kPresetDefs[] and registers
// each preset with the plugin. It handles both default presets and custom
// presets with specific parameter values.
//
// ═══════════════════════════════════════════════════════════════════════════════

// NOTE: This file must be included AFTER Plugin.h in Plugin.cpp
// It uses iplug::Plugin class from those headers.

// ═══════════════════════════════════════════════════════════════════════════════
// NO VALIDATION NEEDED!
// Presets now use kParamXxx values directly from Plugin_Params.h.
// No P:: namespace, no manual index sync - just the actual enum values.
// ═══════════════════════════════════════════════════════════════════════════════

inline void InitPresets(iplug::Plugin* pPlugin)
{
  for (int i = 0; i < kPresetCount; i++)
  {
    const PresetDef& preset = kPresetDefs[i];

    if (preset.isDefault)
    {
      // Default preset - uses all default parameter values
      pPlugin->MakeDefaultPreset(preset.name);
    }
    else
    {
      // Custom preset - count params and apply them
      // First, count parameters (until END sentinel)
      int paramCount = 0;
      while (paramCount < kMaxPresetParams && preset.params[paramCount].idx != END)
      {
        paramCount++;
      }

      // Reset ALL params to their defaults first
      // This ensures we don't inherit values from previous presets
      for (int p = 0; p < kNumParams; p++)
      {
        pPlugin->GetParam(p)->SetToDefault();
      }

      // Then set custom parameters for this preset
      for (int p = 0; p < paramCount; p++)
      {
        pPlugin->GetParam(preset.params[p].idx)->Set(preset.params[p].val);
      }

      // Now create the preset - it will capture the values we just set
      pPlugin->MakeDefaultPreset(preset.name);
    }
  }

  // Reset to first preset after initialization
  pPlugin->RestorePreset(0);
}
