/**
 * AUTO-GENERATED BY build-flow
 * DO NOT EDIT MANUALLY
 *
 * Golden Effect - Dattorro Plate Reverb
 * Runtime parameters for UI binding
 */

export type RuntimeParameter = {
  id: number;
  name: string;
  type: string;
  min: number;
  max: number;
  default: number;
  step: number;
  unit: string;
  group: string;
  shape: string;
  shapeParameter: number;
  enumValues: string[] | null;
  automatable: boolean;
  key: string;
};

export type ControlTag = {
  id: number;
  key: string;
  senderType: 'ISender' | 'IPeakSender' | 'IPeakAvgSender' | 'IBufferSender' | 'ISpectrumSender' | null;
  channels: number | null;
};

export type MsgTag = {
  id: number;
  key: string;
};

export const runtimeParameters: RuntimeParameter[] = [
  // === MIX SECTION ===
  {
    "id": 0,
    "name": "Dry",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 100,
    "step": 0.1,
    "unit": "%",
    "group": "Mix",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDry"
  },
  {
    "id": 1,
    "name": "Wet",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 30,
    "step": 0.1,
    "unit": "%",
    "group": "Mix",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamWet"
  },

  // === CHARACTER SECTION ===
  {
    "id": 2,
    "name": "Size",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 70,
    "step": 0.1,
    "unit": "%",
    "group": "Character",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamSize"
  },
  {
    "id": 3,
    "name": "Decay",
    "type": "float",
    "min": 0,
    "max": 99,
    "default": 70,
    "step": 0.1,
    "unit": "%",
    "group": "Character",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDecay"
  },
  {
    "id": 4,
    "name": "Pre-Delay",
    "type": "float",
    "min": 0,
    "max": 200,
    "default": 10,
    "step": 0.1,
    "unit": "ms",
    "group": "Character",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamPreDelay"
  },
  {
    "id": 5,
    "name": "Diffusion",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 75,
    "step": 0.1,
    "unit": "%",
    "group": "Character",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDiffusion"
  },

  // Density controls the tank allpass feedback - texture of the tail
  // Low = grainy, you hear individual reflections
  // High = smooth, continuous wash
  {
    "id": 6,
    "name": "Density",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 70,
    "step": 0.1,
    "unit": "%",
    "group": "Character",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDensity"
  },

  // === TONE SECTION ===
  {
    "id": 7,
    "name": "Damping",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 50,
    "step": 0.1,
    "unit": "%",
    "group": "Tone",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDamping"
  },
  {
    "id": 8,
    "name": "Low Cut",
    "type": "float",
    "min": 20,
    "max": 1000,
    "default": 80,
    "step": 1,
    "unit": "Hz",
    "group": "Tone",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamLowCut"
  },
  {
    "id": 9,
    "name": "High Cut",
    "type": "float",
    "min": 500,
    "max": 20000,
    "default": 8000,
    "step": 10,
    "unit": "Hz",
    "group": "Tone",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamHighCut"
  },

  // === MODULATION SECTION ===
  {
    "id": 10,
    "name": "Mod Rate",
    "type": "float",
    "min": 0.1,
    "max": 2,
    "default": 0.5,
    "step": 0.01,
    "unit": "Hz",
    "group": "Modulation",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamModRate"
  },
  {
    "id": 11,
    "name": "Mod Depth",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 50,
    "step": 0.1,
    "unit": "%",
    "group": "Modulation",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamModDepth"
  },

  // === OUTPUT SECTION ===
  {
    "id": 12,
    "name": "Width",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 100,
    "step": 0.1,
    "unit": "%",
    "group": "Output",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamWidth"
  },

  // === EARLY/LATE SECTION ===
  {
    "id": 13,
    "name": "Early/Late",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 50,
    "step": 0.1,
    "unit": "%",
    "group": "Character",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamEarlyLate"
  }
];

export const controlTags: ControlTag[] = [
  {
    "id": 0,
    "key": "kCtrlTagMeter",
    "senderType": "IPeakAvgSender",
    "channels": 2
  }
];

export const msgTags: MsgTag[] = [];

// Convenience lookups (type-safe)
export const EParams = {
  kParamDry: 0,
  kParamWet: 1,
  kParamSize: 2,
  kParamDecay: 3,
  kParamPreDelay: 4,
  kParamDiffusion: 5,
  kParamDensity: 6,
  kParamDamping: 7,
  kParamLowCut: 8,
  kParamHighCut: 9,
  kParamModRate: 10,
  kParamModDepth: 11,
  kParamWidth: 12,
  kParamEarlyLate: 13,
} as const;

export const EControlTags = {
  kCtrlTagMeter: 0,
} as const;

export const EMsgTags = {

} as const;

// Type helpers
export type EParamsKey = keyof typeof EParams;
export type EControlTagsKey = keyof typeof EControlTags;
export type EMsgTagsKey = keyof typeof EMsgTags;
