/**
 * AUTO-GENERATED BY build-flow
 * DO NOT EDIT MANUALLY
 */

export type RuntimeParameter = {
  id: number;
  name: string;
  type: string;
  min: number;
  max: number;
  default: number;
  step: number;
  unit: string;
  group: string;
  shape: string;
  shapeParameter: number;
  enumValues: string[] | null;
  automatable: boolean;
  key: string;
};

export type ControlTag = {
  id: number;
  key: string;
  senderType: 'ISender' | 'IPeakSender' | 'IPeakAvgSender' | 'IBufferSender' | 'ISpectrumSender' | null;
  channels: number | null;
};

export type MsgTag = {
  id: number;
  key: string;
};

export const runtimeParameters: RuntimeParameter[] = [
  {
    "id": 0,
    "name": "Gain",
    "type": "float",
    "min": 0,
    "max": 200,
    "default": 100,
    "step": 0.01,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamGain"
  },
  {
    "id": 1,
    "name": "Delay Time",
    "type": "float",
    "min": 1,
    "max": 2000,
    "default": 250,
    "step": 1,
    "unit": "ms",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDelayTime"
  },
  {
    "id": 2,
    "name": "Feedback",
    "type": "float",
    "min": 0,
    "max": 95,
    "default": 30,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDelayFeedback"
  },
  {
    "id": 3,
    "name": "Dry",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 100,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDelayDry"
  },
  {
    "id": 4,
    "name": "Wet",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 25,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDelayWet"
  },
  {
    "id": 5,
    "name": "Sync",
    "type": "bool",
    "min": 0,
    "max": 1,
    "default": 0,
    "step": 1,
    "unit": "",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDelaySync"
  },
  {
    "id": 6,
    "name": "Division",
    "type": "enum",
    "min": 0,
    "max": 7,
    "default": 2,
    "step": 1,
    "unit": "",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": [
      "1/1",
      "1/2",
      "1/4",
      "1/8",
      "1/16",
      "1/32",
      "1/4T",
      "1/8T"
    ],
    "automatable": true,
    "key": "kParamDelayDivision"
  },
  {
    "id": 7,
    "name": "Reverb On",
    "type": "bool",
    "min": 0,
    "max": 1,
    "default": 0,
    "step": 1,
    "unit": "",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamReverbOn"
  },
  {
    "id": 8,
    "name": "Reverb Mix",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 25,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamReverbMix"
  },
  {
    "id": 9,
    "name": "Room Size",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 50,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamReverbSize"
  },
  {
    "id": 10,
    "name": "Decay",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 50,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamReverbDecay"
  },
  {
    "id": 11,
    "name": "Damping",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 50,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamReverbDamping"
  },
  {
    "id": 12,
    "name": "Pre-Delay",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 20,
    "step": 0.1,
    "unit": "ms",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamReverbPreDelay"
  },
  {
    "id": 13,
    "name": "Width",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 100,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamReverbWidth"
  },
  {
    "id": 14,
    "name": "Low Cut",
    "type": "float",
    "min": 20,
    "max": 500,
    "default": 80,
    "step": 1,
    "unit": "Hz",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamReverbLowCut"
  }
];

export const controlTags: ControlTag[] = [
  {
    "id": 0,
    "key": "kCtrlTagMeter",
    "senderType": "IPeakAvgSender",
    "channels": 2
  },
  {
    "id": 1,
    "key": "kCtrlTagDelayTime",
    "senderType": null,
    "channels": null
  },
  {
    "id": 2,
    "key": "kCtrlTagReverbSection",
    "senderType": null,
    "channels": null
  }
];

export const msgTags: MsgTag[] = [];

// Convenience lookups (type-safe)
export const EParams = {
  kParamGain: 0,
  kParamDelayTime: 1,
  kParamDelayFeedback: 2,
  kParamDelayDry: 3,
  kParamDelayWet: 4,
  kParamDelaySync: 5,
  kParamDelayDivision: 6,
  kParamReverbOn: 7,
  kParamReverbMix: 8,
  kParamReverbSize: 9,
  kParamReverbDecay: 10,
  kParamReverbDamping: 11,
  kParamReverbPreDelay: 12,
  kParamReverbWidth: 13,
  kParamReverbLowCut: 14,
} as const;

export const EControlTags = {
  kCtrlTagMeter: 0,
  kCtrlTagDelayTime: 1,
  kCtrlTagReverbSection: 2,
} as const;

export const EMsgTags = {

} as const;

// Type helpers
export type EParamsKey = keyof typeof EParams;
export type EControlTagsKey = keyof typeof EControlTags;
export type EMsgTagsKey = keyof typeof EMsgTags;
