/**
 * AUTO-GENERATED BY build-flow
 * DO NOT EDIT MANUALLY
 */

export type RuntimeParameter = {
  id: number;
  name: string;
  type: string;
  min: number;
  max: number;
  default: number;
  step: number;
  unit: string;
  group: string;
  shape: string;
  shapeParameter: number;
  enumValues: string[] | null;
  automatable: boolean;
  key: string;
};

export type ControlTag = {
  id: number;
  key: string;
  senderType: 'ISender' | 'IPeakSender' | 'IPeakAvgSender' | 'IBufferSender' | 'ISpectrumSender' | null;
  channels: number | null;
};

export type MsgTag = {
  id: number;
  key: string;
};

export const runtimeParameters: RuntimeParameter[] = [
  {
    "id": 0,
    "name": "Delay Time",
    "type": "float",
    "min": 10,
    "max": 1000,
    "default": 300,
    "step": 0.1,
    "unit": "ms",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDelayTime"
  },
  {
    "id": 1,
    "name": "Feedback",
    "type": "float",
    "min": 0,
    "max": 95,
    "default": 40,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDelayFeedback"
  },
  {
    "id": 2,
    "name": "Mix",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 50,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDelayMix"
  }
];

export const controlTags: ControlTag[] = [
  {
    "id": 0,
    "key": "kCtrlTagMeter",
    "senderType": "IPeakAvgSender",
    "channels": 2
  },
  {
    "id": 1,
    "key": "kCtrlTagWaveform",
    "senderType": "IBufferSender",
    "channels": 1
  }
];

export const msgTags: MsgTag[] = [];

// Convenience lookups (type-safe)
export const EParams = {
  kParamDelayTime: 0,
  kParamDelayFeedback: 1,
  kParamDelayMix: 2,
} as const;

export const EControlTags = {
  kCtrlTagMeter: 0,
  kCtrlTagWaveform: 1,
} as const;

export const EMsgTags = {

} as const;

// Type helpers
export type EParamsKey = keyof typeof EParams;
export type EControlTagsKey = keyof typeof EControlTags;
export type EMsgTagsKey = keyof typeof EMsgTags;
