/**
 * AUTO-GENERATED BY build-flow
 * DO NOT EDIT MANUALLY
 */

export type RuntimeParameter = {
  id: number;
  name: string;
  type: string;
  min: number;
  max: number;
  default: number;
  step: number;
  unit: string;
  group: string;
  shape: string;
  shapeParameter: number;
  enumValues: string[] | null;
  automatable: boolean;
  key: string;
};

export type ControlTag = {
  id: number;
  key: string;
};

export const runtimeParameters: RuntimeParameter[] = [
  {
    "id": 0,
    "name": "Gain",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 80,
    "step": 0.01,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamGain"
  }
];

export const controlTags: ControlTag[] = [
  {
    "id": 0,
    "key": "kCtrlTagMeter"
  }
];

// Convenience lookups (type-safe)
export const EParams = {
  kParamGain: 0,
} as const;

export const EControlTags = {
  kCtrlTagMeter: 0,
} as const;

// Type helpers
export type EParamsKey = keyof typeof EParams;
export type EControlTagsKey = keyof typeof EControlTags;
