/**
 * AUTO-GENERATED BY build-flow
 * DO NOT EDIT MANUALLY
 */

export type RuntimeParameter = {
  id: number;
  name: string;
  type: string;
  min: number;
  max: number;
  default: number;
  step: number;
  unit: string;
  group: string;
  shape: string;
  shapeParameter: number;
  enumValues: string[] | null;
  automatable: boolean;
};

export const runtimeParameters: RuntimeParameter[] = [];
