/**
 * AUTO-GENERATED BY build-flow
 * DO NOT EDIT MANUALLY
 */

export type RuntimeParameter = {
  id: number;
  name: string;
  type: string;
  min: number;
  max: number;
  default: number;
  step: number;
  unit: string;
  group: string;
  shape: string;
  shapeParameter: number;
  enumValues: string[] | null;
  automatable: boolean;
  key: string;
};

export type ControlTag = {
  id: number;
  key: string;
  senderType: 'ISender' | 'IPeakSender' | 'IPeakAvgSender' | 'IBufferSender' | 'ISpectrumSender' | null;
  channels: number | null;
};

export type MsgTag = {
  id: number;
  key: string;
};

export const runtimeParameters: RuntimeParameter[] = [
  {
    "id": 0,
    "name": "Gain",
    "type": "float",
    "min": 0,
    "max": 200,
    "default": 100,
    "step": 0.01,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamGain"
  },
  {
    "id": 1,
    "name": "Delay Time",
    "type": "float",
    "min": 10,
    "max": 2000,
    "default": 300,
    "step": 1,
    "unit": "ms",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDelayTime"
  },
  {
    "id": 2,
    "name": "Feedback",
    "type": "float",
    "min": 0,
    "max": 95,
    "default": 30,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDelayFeedback"
  },
  {
    "id": 3,
    "name": "Dry",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 100,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDelayDry"
  },
  {
    "id": 4,
    "name": "Wet",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 50,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamDelayWet"
  },
  {
    "id": 5,
    "name": "Chorus Rate",
    "type": "float",
    "min": 0.1,
    "max": 5,
    "default": 0.5,
    "step": 0.01,
    "unit": "Hz",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamChorusRate"
  },
  {
    "id": 6,
    "name": "Chorus Depth",
    "type": "float",
    "min": 0.5,
    "max": 20,
    "default": 5,
    "step": 0.1,
    "unit": "ms",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamChorusDepth"
  },
  {
    "id": 7,
    "name": "Chorus Dry",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 100,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamChorusDry"
  },
  {
    "id": 8,
    "name": "Chorus Wet",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 50,
    "step": 0.1,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamChorusWet"
  }
];

export const controlTags: ControlTag[] = [
  {
    "id": 0,
    "key": "kCtrlTagMeter",
    "senderType": "IPeakAvgSender",
    "channels": 2
  }
];

export const msgTags: MsgTag[] = [];

// Convenience lookups (type-safe)
export const EParams = {
  kParamGain: 0,
  kParamDelayTime: 1,
  kParamDelayFeedback: 2,
  kParamDelayDry: 3,
  kParamDelayWet: 4,
  kParamChorusRate: 5,
  kParamChorusDepth: 6,
  kParamChorusDry: 7,
  kParamChorusWet: 8,
} as const;

export const EControlTags = {
  kCtrlTagMeter: 0,
} as const;

export const EMsgTags = {

} as const;

// Type helpers
export type EParamsKey = keyof typeof EParams;
export type EControlTagsKey = keyof typeof EControlTags;
export type EMsgTagsKey = keyof typeof EMsgTags;
