/**
 * AUTO-GENERATED BY build-flow
 * DO NOT EDIT MANUALLY
 */

export type RuntimeParameter = {
  id: number;
  name: string;
  type: string;
  min: number;
  max: number;
  default: number;
  step: number;
  unit: string;
  group: string;
  shape: string;
  shapeParameter: number;
  enumValues: string[] | null;
  automatable: boolean;
  key: string;
};

export type ControlTag = {
  id: number;
  key: string;
  senderType: 'ISender' | 'IPeakSender' | 'IPeakAvgSender' | 'IBufferSender' | 'ISpectrumSender' | null;
  channels: number | null;
};

export type MsgTag = {
  id: number;
  key: string;
};

export const runtimeParameters: RuntimeParameter[] = [
  {
    "id": 0,
    "name": "Gain",
    "type": "float",
    "min": 0,
    "max": 100,
    "default": 80,
    "step": 0.01,
    "unit": "%",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamGain"
  },
  {
    "id": 1,
    "name": "Kick Pitch Start",
    "type": "float",
    "min": 100,
    "max": 500,
    "default": 300,
    "step": 1,
    "unit": "Hz",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamKickPitchStart"
  },
  {
    "id": 2,
    "name": "Kick Pitch End",
    "type": "float",
    "min": 30,
    "max": 150,
    "default": 50,
    "step": 1,
    "unit": "Hz",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamKickPitchEnd"
  },
  {
    "id": 3,
    "name": "Kick Pitch Decay",
    "type": "float",
    "min": 10,
    "max": 200,
    "default": 50,
    "step": 1,
    "unit": "ms",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamKickPitchDecay"
  },
  {
    "id": 4,
    "name": "Kick Amp Decay",
    "type": "float",
    "min": 50,
    "max": 1000,
    "default": 300,
    "step": 1,
    "unit": "ms",
    "group": "",
    "shape": "ShapeLinear",
    "shapeParameter": 0,
    "enumValues": null,
    "automatable": true,
    "key": "kParamKickAmpDecay"
  }
];

export const controlTags: ControlTag[] = [
  {
    "id": 0,
    "key": "kCtrlTagMeter",
    "senderType": "IPeakAvgSender",
    "channels": 2
  }
];

export const msgTags: MsgTag[] = [];

// Voice configuration for drum machines (used by StepSequencer)
export type VoiceConfig = {
  name: string;
  midiNote: number;
};

export const voiceConfig: VoiceConfig[] = [
  {
    "name": "KICK",
    "midiNote": 48
  }
];

// Convenience lookups (type-safe)
export const EParams = {
  kParamGain: 0,
  kParamKickPitchStart: 1,
  kParamKickPitchEnd: 2,
  kParamKickPitchDecay: 3,
  kParamKickAmpDecay: 4,
} as const;

export const EControlTags = {
  kCtrlTagMeter: 0,
} as const;

export const EMsgTags = {

} as const;

// Type helpers
export type EParamsKey = keyof typeof EParams;
export type EControlTagsKey = keyof typeof EControlTags;
export type EMsgTagsKey = keyof typeof EMsgTags;
